#created by travis-deploy-ssh

#env:
# - DEPLOY_HOST=
# - DEPLOY_USER=
# - DEPLOY_PASSWORD=
# - DEPLOY_TARGET_FILE=
language: generic
before_deploy:
 - chmod u+x node_modules/travis-deploy-ssh/deploy.sh
deploy:
 provider: script
 skip_cleanup: true
 script: node_modules/travis-deploy-ssh/deploy.sh
